Vagrant.configure("2") do |config|
  # Usa una imagen ligera de Ubuntu 22.04
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  
  # Configuración de red (accesible via IP)
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Provisionamiento con Shell
  config.vm.provision "shell", path: "scripts/install_nginx.sh"
  config.vm.provision "shell", path: "scripts/install_git.sh"
end